---
language: python
dist: xenial
# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
python: 2.7

env:
  matrix:
    - OMERO_VERSION=5.2
    - OMERO_VERSION=5.3
    - OMERO_VERSION=5.4
    - OMERO_VERSION=5.5

before_install:
  # The installation of the python dependencies must be done in that level for now
  # otherwise they are not available in the containers,
  # see https://github.com/travis-ci/travis-ci/issues/8048
  # Changing the value for sudo will also need to be reviewed at the same time
  # This will need to be reviewed when the issue above is fixed
  - export PATH=/usr/bin/:$PATH
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu`lsb_release -rs` stable main"
  - sudo apt-get update
  - sudo apt-get -y install zeroc-ice-all-runtime
  - pip install -U https://github.com/ome/zeroc-ice-py-ubuntu1604/releases/download/0.1.0/zeroc_ice-3.6.4-cp27-cp27mu-linux_x86_64.whl
  - pip install omego
  - omego download --ice 3.6 --release ${OMERO_VERSION} py
  - rm OMERO.py*.zip
  - mv OMERO.py* /tmp/OMERO.py
  - pip install flake8
  - flake8 .

script:
    - PYTHONPATH=/tmp/OMERO.py/lib/python python setup.py test --pytest-args='-v -v'
    - python setup.py sdist install --record files.txt
    - PYTHONPATH=/tmp/OMERO.py/lib/python python -c 'import omero.clients; import omero_marshal.encode'
    - cat files.txt | xargs sudo rm -rf
    - python setup.py bdist_egg
    - easy_install dist/*.egg
    - PYTHONPATH=/tmp/OMERO.py/lib/python python -c 'import omero.clients; import omero_marshal.encode'

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
